// Gegenereerd door build.py op 2026-09-15 16:38
window.HOUSES = [
 {
  "id": "1128",
  "name": "Villa Can Bernardi",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/vidreres/villa-can-bernardi.html",
  "town": "Vidreres",
  "area": "Countryside",
  "lat": 41.80531,
  "lng": 2.78321,
  "persons": 21,
  "personsMax": 26,
  "bedrooms": 10,
  "bathrooms": 7,
  "beds": {},
  "m2": 450,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": false,
  "groups": "geen groepen",
  "minAge": null,
  "rating": 3,
  "reviews": 7,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1128/villa-can-bernardi_17903_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1128/villa-can-bernardi_17921_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1128/villa-can-bernardi_17882_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1128/villa-can-bernardi_17904_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1128/villa-can-bernardi_17922_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1128/villa-can-bernardi_17905_X.jpg"
  ]
 },
 {
  "id": "1102",
  "name": "Villa Pilar",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/casa-pilar.html",
  "town": "Lloret de Mar",
  "area": "Lloret Center",
  "lat": 41.70421,
  "lng": 2.85921,
  "persons": 21,
  "personsMax": 23,
  "bedrooms": 10,
  "bathrooms": 7,
  "beds": {
   "Single": 20,
   "Double": 2
  },
  "m2": 240,
  "pool": true,
  "poolType": "Outdoor",
  "pets": false,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 4,
  "reviews": 34,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1102/villa-pilar_19928_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1102/villa-pilar_19932_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1102/villa-pilar_19929_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1102/villa-pilar_19927_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1102/villa-pilar_19931_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1102/villa-pilar_19918_X.jpg"
  ]
 },
 {
  "id": "1027",
  "name": "Villa Jaruco",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-jaruco.html",
  "town": "Lloret de Mar",
  "area": "Condado del Jaruco",
  "lat": 41.71151,
  "lng": 2.82681,
  "persons": 18,
  "personsMax": 22,
  "bedrooms": 9,
  "bathrooms": 6,
  "beds": {
   "Single": 4,
   "Double": 8
  },
  "m2": 460,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 3.5,
  "reviews": 43,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1027/villa-jaruco_17451_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1027/villa-jaruco_17473_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1027/villa-jaruco_17449_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1027/villa-jaruco_17475_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1027/villa-jaruco_17470_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1027/villa-jaruco_17474_X.jpg"
  ]
 },
 {
  "id": "1016",
  "name": "Villa Geolouk",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-geolouk.html",
  "town": "Lloret de Mar",
  "area": "Aigua Viva Park",
  "lat": 41.75841,
  "lng": 2.80061,
  "persons": 16,
  "personsMax": 16,
  "bedrooms": 6,
  "bathrooms": 4,
  "beds": {
   "Single": 8,
   "Double": 4
  },
  "m2": 400,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": false,
  "groups": "gemengde groepen",
  "minAge": 21,
  "rating": 3.5,
  "reviews": 22,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1016/villa-geolouk_17945_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1016/villa-geolouk_17944_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1016/villa-geolouk_17947_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1016/villa-geolouk_17943_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1016/villa-geolouk_17946_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1016/villa-geolouk_17942_X.jpg"
  ]
 },
 {
  "id": "1099",
  "name": "Villa Nicky",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-nicky.html",
  "town": "Lloret de Mar",
  "area": "Condado del Jaruco",
  "lat": 41.71161,
  "lng": 2.82681,
  "persons": 16,
  "personsMax": 18,
  "bedrooms": 7,
  "bathrooms": 3.5,
  "beds": {
   "Single": 14,
   "Double": 2
  },
  "m2": 250,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 3.5,
  "reviews": 48,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1099/villa-nicky_17973_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1099/villa-nicky_17972_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1099/villa-nicky_17974_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1099/villa-nicky_17975_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1099/villa-nicky_17976_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1099/villa-nicky_17991_X.jpg"
  ]
 },
 {
  "id": "1101",
  "name": "Villa Ashley",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-ashley.html",
  "town": "Lloret de Mar",
  "area": "Condado del Jaruco",
  "lat": 41.71231,
  "lng": 2.82641,
  "persons": 15,
  "personsMax": 17,
  "bedrooms": 6,
  "bathrooms": 4,
  "beds": {
   "Single": 6,
   "Double": 6
  },
  "m2": 350,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 4,
  "reviews": 7,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1101/villa-ashley_17839_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1101/villa-ashley_17838_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1101/villa-ashley_17844_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1101/villa-ashley_17842_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1101/villa-ashley_17843_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1101/villa-ashley_17841_X.jpg"
  ]
 },
 {
  "id": "1281",
  "name": "Villa Grace",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/blanes/villa-grace.html",
  "town": "Blanes",
  "area": "Mas Mora",
  "lat": 41.71481,
  "lng": 2.75431,
  "persons": 14,
  "personsMax": 16,
  "bedrooms": 8,
  "bathrooms": 5,
  "beds": {
   "Single": 8,
   "Double": 4
  },
  "m2": 480,
  "pool": true,
  "poolType": "Outdoor",
  "pets": false,
  "aircoPaid": false,
  "groups": "gemengde groepen",
  "minAge": 24,
  "rating": 4,
  "reviews": 4,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1281/villa-grace_16752_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1281/villa-grace_16736_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1281/villa-grace_16737_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1281/villa-grace_16760_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1281/villa-grace_16754_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1281/villa-grace_16739_X.jpg"
  ]
 },
 {
  "id": "1247",
  "name": "Villa Madonna",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-madonna.html",
  "town": "Lloret de Mar",
  "area": "Condado del Jaruco",
  "lat": 41.70681,
  "lng": 2.82291,
  "persons": 14,
  "personsMax": 16,
  "bedrooms": 8,
  "bathrooms": 3,
  "beds": {
   "Single": 7,
   "Double": 3,
   "King": 1
  },
  "m2": 250,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": true,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 4,
  "reviews": 26,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1247/villa-madonna_17037_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1247/villa-madonna_17034_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1247/villa-madonna_17032_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1247/villa-madonna_17035_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1247/villa-madonna_17033_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1247/villa-madonna_17029_X.jpg"
  ]
 },
 {
  "id": "1467",
  "name": "Villa Marysol",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-marysol.html",
  "town": "Lloret de Mar",
  "area": "Rocca Grossa",
  "lat": 41.71651,
  "lng": 2.85151,
  "persons": 14,
  "personsMax": 17,
  "bedrooms": 8,
  "bathrooms": 5,
  "beds": {
   "Single": 13,
   "Double": 2
  },
  "m2": 300,
  "pool": true,
  "poolType": "Outdoor",
  "pets": false,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 4,
  "reviews": 3,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1467/villa-marysol_20328_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1467/villa-marysol_20329_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1467/villa-marysol_20331_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1467/villa-marysol_20330_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1467/villa-marysol_20327_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1467/villa-marysol_20320_X.jpg"
  ]
 },
 {
  "id": "1465",
  "name": "Villa Summertime",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-summertime.html",
  "town": "Lloret de Mar",
  "area": "Lloret Center",
  "lat": 41.70461,
  "lng": 2.85251,
  "persons": 14,
  "personsMax": 16,
  "bedrooms": 7,
  "bathrooms": 4,
  "beds": {
   "Single": 6,
   "Double": 4,
   "King": 1
  },
  "m2": 200,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": true,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 4.5,
  "reviews": 9,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1465/villa-summertime_20153_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1465/villa-summertime_20189_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1465/villa-summertime_20168_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1465/villa-summertime_20169_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1465/villa-summertime_20167_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1465/villa-summertime_20171_X.jpg"
  ]
 },
 {
  "id": "1015",
  "name": "Villa Estrella",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-estrella.html",
  "town": "Lloret de Mar",
  "area": "Montgoda",
  "lat": 41.70261,
  "lng": 2.86971,
  "persons": 12,
  "personsMax": 14,
  "bedrooms": 6,
  "bathrooms": 3,
  "beds": {
   "Single": 4,
   "Double": 5
  },
  "m2": 200,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 4,
  "reviews": 24,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1015/villa-estrella_19364_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1015/villa-estrella_19353_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1015/villa-estrella_19352_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1015/villa-estrella_19351_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1015/villa-estrella_19365_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1015/villa-estrella_19366_X.jpg"
  ]
 },
 {
  "id": "1462",
  "name": "Villa Maribel",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-maribel.html",
  "town": "Lloret de Mar",
  "area": "Rocca Grossa",
  "lat": 41.71201,
  "lng": 2.85131,
  "persons": 12,
  "personsMax": 13,
  "bedrooms": 6,
  "bathrooms": 4.5,
  "beds": {
   "Single": 5,
   "Double": 4
  },
  "m2": 225,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 4,
  "reviews": 4,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1462/villa-maribel_20005_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1462/villa-maribel_20009_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1462/villa-maribel_20011_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1462/villa-maribel_20007_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1462/villa-maribel_20004_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1462/villa-maribel_20006_X.jpg"
  ]
 },
 {
  "id": "1357",
  "name": "Villa Dolce Vita",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-dolce-vita.html",
  "town": "Lloret de Mar",
  "area": "Lloret Center",
  "lat": 41.69751,
  "lng": 2.83611,
  "persons": 11,
  "personsMax": 11,
  "bedrooms": 6,
  "bathrooms": 4.5,
  "beds": {
   "Single": 13
  },
  "m2": 180,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": true,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 4,
  "reviews": 12,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1357/villa-dolce-vita_17361_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1357/villa-dolce-vita_17360_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1357/villa-dolce-vita_17362_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1357/villa-dolce-vita_17365_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1357/villa-dolce-vita_17357_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1357/villa-dolce-vita_17358_X.jpg"
  ]
 },
 {
  "id": "1452",
  "name": "Villa Primavera",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-primavera.html",
  "town": "Lloret de Mar",
  "area": "Condado del Jaruco",
  "lat": 41.70891,
  "lng": 2.82341,
  "persons": 11,
  "personsMax": 13,
  "bedrooms": 5,
  "bathrooms": 3,
  "beds": {
   "Single": 7,
   "Double": 3,
   "King": 1
  },
  "m2": 379,
  "pool": true,
  "poolType": "Outdoor",
  "pets": false,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 4,
  "reviews": 2,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1452/villa-primavera_19752_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1452/villa-primavera_19751_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1452/villa-primavera_19748_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1452/villa-primavera_19750_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1452/villa-primavera_19990_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1452/villa-primavera_19988_X.jpg"
  ]
 },
 {
  "id": "1454",
  "name": "Villa Sunrise",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-sunrise.html",
  "town": "Lloret de Mar",
  "area": "de wijk Roca Grossa",
  "lat": 41.71391,
  "lng": 2.85591,
  "persons": 11,
  "personsMax": 11,
  "bedrooms": 5,
  "bathrooms": 5,
  "beds": {
   "Single": 11
  },
  "m2": 242,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 4,
  "reviews": 6,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1454/villa-sunrise_19915_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1454/villa-sunrise_19914_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1454/villa-sunrise_19916_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1454/villa-sunrise_19917_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1454/villa-sunrise_19911_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1454/villa-sunrise_19905_X.jpg"
  ]
 },
 {
  "id": "1110",
  "name": "Villa Alba",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-alba.html",
  "town": "Lloret de Mar",
  "area": "Font de Sant Llorenc",
  "lat": 41.71171,
  "lng": 2.87691,
  "persons": 10,
  "personsMax": 10,
  "bedrooms": 4,
  "bathrooms": 2,
  "beds": {
   "Double": 5,
   "SofaBed": 1
  },
  "m2": 120,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 4,
  "reviews": 37,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1110/villa-alba_19709_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1110/villa-alba_19710_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1110/villa-alba_19715_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1110/villa-alba_17815_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1110/villa-alba_19707_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1110/villa-alba_19711_X.jpg"
  ]
 },
 {
  "id": "1168",
  "name": "Villa Baileys",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-baileys.html",
  "town": "Lloret de Mar",
  "area": "Fenals",
  "lat": 41.70141,
  "lng": 2.83301,
  "persons": 10,
  "personsMax": 11,
  "bedrooms": 5,
  "bathrooms": 4,
  "beds": {
   "Single": 5,
   "Double": 3
  },
  "m2": 420,
  "pool": true,
  "poolType": "Outdoor",
  "pets": false,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 4,
  "reviews": 19,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1168/villa-baileys_18068_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1168/villa-baileys_18061_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1168/villa-baileys_18059_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1168/villa-baileys_18063_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1168/villa-baileys_18066_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1168/villa-baileys_18075_X.jpg"
  ]
 },
 {
  "id": "1476",
  "name": "Villa Ibiza",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/blanes/villa-ibiza.html",
  "town": "Blanes",
  "area": "Rocca Grossa",
  "lat": 41.71151,
  "lng": 2.85151,
  "persons": 10,
  "personsMax": 12,
  "bedrooms": 4,
  "bathrooms": 3,
  "beds": {
   "Single": 6,
   "Double": 2
  },
  "m2": 180,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": true,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 4.5,
  "reviews": 1,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1476/villa-ibiza_20698_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1476/villa-ibiza_20699_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1476/villa-ibiza_20701_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1476/villa-ibiza_20702_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1476/villa-ibiza_20697_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1476/villa-ibiza_20700_X.jpg"
  ]
 },
 {
  "id": "1139",
  "name": "Villa Infinity",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-infinity.html",
  "town": "Lloret de Mar",
  "area": "Canyelles",
  "lat": 41.70181,
  "lng": 2.87731,
  "persons": 10,
  "personsMax": 10,
  "bedrooms": 5,
  "bathrooms": 4.5,
  "beds": {
   "Double": 3,
   "King": 2
  },
  "m2": 500,
  "pool": true,
  "poolType": "Outdoor",
  "pets": false,
  "aircoPaid": false,
  "groups": "gemengde groepen",
  "minAge": 24,
  "rating": 4.5,
  "reviews": 5,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1139/villa-infinity_20459_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1139/villa-infinity_20461_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1139/villa-infinity_20464_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1139/villa-infinity_20460_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1139/villa-infinity_20453_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1139/villa-infinity_20465_X.jpg"
  ]
 },
 {
  "id": "1049",
  "name": "Villa Paris",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-paris.html",
  "town": "Lloret de Mar",
  "area": "Rocca Grossa",
  "lat": 41.71441,
  "lng": 2.85051,
  "persons": 10,
  "personsMax": 11,
  "bedrooms": 5,
  "bathrooms": 3,
  "beds": {
   "Single": 11
  },
  "m2": 248,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 3,
  "reviews": 38,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1049/villa-paris_18609_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1049/villa-paris_18611_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1049/villa-paris_18608_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1049/villa-paris_18606_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1049/villa-paris_18605_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1049/villa-paris_18607_X.jpg"
  ]
 },
 {
  "id": "1013",
  "name": "Villa Sofia",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-sofia.html",
  "town": "Lloret de Mar",
  "area": "Lloret Blau",
  "lat": 41.74011,
  "lng": 2.81291,
  "persons": 10,
  "personsMax": 10,
  "bedrooms": 4,
  "bathrooms": 3,
  "beds": {
   "Single": 6,
   "Double": 2
  },
  "m2": 190,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 4,
  "reviews": 24,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1013/villa-sofia_17836_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1013/villa-sofia_17835_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1013/villa-sofia_17833_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1013/villa-sofia_17837_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1013/villa-sofia_17832_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1013/villa-sofia_17834_X.jpg"
  ]
 },
 {
  "id": "1059",
  "name": "Villa Valentina",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-valentina.html",
  "town": "Lloret de Mar",
  "area": "Lloret Dalt",
  "lat": 41.70741,
  "lng": 2.85841,
  "persons": 10,
  "personsMax": 14,
  "bedrooms": 5,
  "bathrooms": 2.5,
  "beds": {
   "Single": 2,
   "Double": 4
  },
  "m2": 250,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 3.5,
  "reviews": 48,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1059/villa-valentina_18905_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1059/villa-valentina_18911_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1059/villa-valentina_18912_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1059/villa-valentina_18913_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1059/villa-valentina_18916_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1059/villa-valentina_18915_X.jpg"
  ]
 },
 {
  "id": "1330",
  "name": "Villa Fransisca",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-fransisca.html",
  "town": "Lloret de Mar",
  "area": "Santa Cristina",
  "lat": 41.68771,
  "lng": 2.80641,
  "persons": 8,
  "personsMax": 8,
  "bedrooms": 4,
  "bathrooms": 2,
  "beds": {
   "Single": 8
  },
  "m2": 160,
  "pool": true,
  "poolType": "Outdoor",
  "pets": false,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 4.5,
  "reviews": 13,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1330/villa-fransisca_20749_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1330/villa-fransisca_18575_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1330/villa-fransisca_18577_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1330/villa-fransisca_18576_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1330/villa-fransisca_18572_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1330/villa-fransisca_18582_X.jpg"
  ]
 },
 {
  "id": "1028",
  "name": "Villa Marcella",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-marcella.html",
  "town": "Lloret de Mar",
  "area": "Rocca Grossa",
  "lat": 41.71331,
  "lng": 2.85011,
  "persons": 8,
  "personsMax": 10,
  "bedrooms": 4,
  "bathrooms": 3,
  "beds": {
   "Double": 4
  },
  "m2": 280,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": true,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 4,
  "reviews": 62,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1028/villa-marcella_20073_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1028/villa-marcella_20072_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1028/villa-marcella_20070_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1028/villa-marcella_20074_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1028/villa-marcella_20071_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1028/villa-marcella_20057_X.jpg"
  ]
 },
 {
  "id": "1122",
  "name": "Villa Mauri",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/blanes/villa-mauri.html",
  "town": "Blanes",
  "area": "San Joan",
  "lat": 41.67831,
  "lng": 2.79581,
  "persons": 8,
  "personsMax": 9,
  "bedrooms": 4,
  "bathrooms": 2.5,
  "beds": {
   "Single": 4,
   "Double": 2
  },
  "m2": 300,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": false,
  "groups": "gemengde groepen",
  "minAge": 24,
  "rating": 3.5,
  "reviews": 25,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1122/villa-mauri_18034_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1122/villa-mauri_18021_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1122/villa-mauri_18027_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1122/villa-mauri_18028_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1122/villa-mauri_18033_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1122/villa-mauri_18036_X.jpg"
  ]
 },
 {
  "id": "1192",
  "name": "Villa Miro",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-miro.html",
  "town": "Lloret de Mar",
  "area": "Condado del Jaruco",
  "lat": 41.70921,
  "lng": 2.82561,
  "persons": 8,
  "personsMax": 8,
  "bedrooms": 4,
  "bathrooms": 3,
  "beds": {
   "Single": 2,
   "Double": 3
  },
  "m2": 350,
  "pool": true,
  "poolType": "Outdoor",
  "pets": false,
  "aircoPaid": false,
  "groups": "gemengde groepen",
  "minAge": 24,
  "rating": 4,
  "reviews": 14,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1192/villa-miro_19053_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1192/villa-miro_19054_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1192/villa-miro_19055_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1192/villa-miro_19052_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1192/villa-miro_19050_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1192/villa-miro_19051_X.jpg"
  ]
 },
 {
  "id": "1455",
  "name": "Villa Palmera",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-palmera.html",
  "town": "Lloret de Mar",
  "area": "Lloret Dalt",
  "lat": 41.70741,
  "lng": 2.86151,
  "persons": 8,
  "personsMax": 9,
  "bedrooms": 4,
  "bathrooms": 2,
  "beds": {
   "Double": 2,
   "King": 2
  },
  "m2": 182,
  "pool": true,
  "poolType": "Outdoor",
  "pets": false,
  "aircoPaid": true,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 4,
  "reviews": 1,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1455/villa-palmera_20495_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1455/villa-davina_20352_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1455/villa-davina_20353_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1455/villa-davina_20347_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1455/villa-davina_20348_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1455/villa-davina_20356_X.jpg"
  ]
 },
 {
  "id": "1071",
  "name": "Villa Rosa",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-rosa.html",
  "town": "Lloret de Mar",
  "area": "Font de Sant Llorenc",
  "lat": 41.71151,
  "lng": 2.87711,
  "persons": 8,
  "personsMax": 10,
  "bedrooms": 4,
  "bathrooms": 3,
  "beds": {
   "Double": 2,
   "King": 2
  },
  "m2": 120,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 3.5,
  "reviews": 31,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1071/villa-rosa_18564_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1071/villa-rosa_18569_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1071/villa-rosa_18563_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1071/villa-rosa_18567_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1071/villa-rosa_18568_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1071/villa-rosa_18565_X.jpg"
  ]
 },
 {
  "id": "1057",
  "name": "Villa Santa Maria",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-santa-maria.html",
  "town": "Lloret de Mar",
  "area": "het hart van een rustige woonwijk",
  "lat": 41.72621,
  "lng": 2.80551,
  "persons": 8,
  "personsMax": 8,
  "bedrooms": 4,
  "bathrooms": 2,
  "beds": {
   "Single": 8
  },
  "m2": 130,
  "pool": true,
  "poolType": "Outdoor",
  "pets": false,
  "aircoPaid": true,
  "groups": "gemengde groepen",
  "minAge": 24,
  "rating": 3.5,
  "reviews": 27,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1057/villa-santa-maria_17741_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1057/villa-santa-maria_17742_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1057/villa-santa-maria_17761_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1057/villa-santa-maria_17744_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1057/villa-santa-maria_17745_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1057/villa-santa-maria_17746_X.jpg"
  ]
 },
 {
  "id": "1072",
  "name": "Villa Sarai",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-sarai.html",
  "town": "Lloret de Mar",
  "area": "Lloret Dalt",
  "lat": 41.70601,
  "lng": 2.85921,
  "persons": 8,
  "personsMax": 10,
  "bedrooms": 4,
  "bathrooms": 2,
  "beds": {
   "Single": 8,
   "Double": 1
  },
  "m2": 150,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": true,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 3.5,
  "reviews": 32,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1072/villa-sarai_19624_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1072/villa-sarai_19625_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1072/villa-sarai_19623_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1072/villa-sarai_18963_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1072/villa-sarai_18952_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1072/villa-sarai_18953_X.jpg"
  ]
 },
 {
  "id": "1035",
  "name": "Villa Lloret",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-lloret.html",
  "town": "Lloret de Mar",
  "area": "Lloret Center",
  "lat": 41.70521,
  "lng": 2.86051,
  "persons": 7,
  "personsMax": 8,
  "bedrooms": 3,
  "bathrooms": 2,
  "beds": {
   "Single": 6,
   "Double": 1
  },
  "m2": 130,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 3.5,
  "reviews": 44,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1035/villa-lloret_17520_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1035/villa-lloret_18076_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1035/villa-lloret_18079_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1035/villa-lloret_18077_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1035/villa-lloret_18078_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1035/villa-lloret_17287_X.jpg"
  ]
 },
 {
  "id": "1065",
  "name": "Villa Donna",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-donna.html",
  "town": "Lloret de Mar",
  "area": "Rocca Grossa",
  "lat": 41.71461,
  "lng": 2.84991,
  "persons": 6,
  "personsMax": 8,
  "bedrooms": 4,
  "bathrooms": 2,
  "beds": {
   "Single": 8
  },
  "m2": 120,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 24,
  "rating": 3.5,
  "reviews": 42,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1065/villa-donna_17511_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1065/villa-donna_17512_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1065/villa-donna_20364_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1065/villa-donna_20365_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1065/villa-donna_20363_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1065/villa-donna_20359_X.jpg"
  ]
 },
 {
  "id": "1254",
  "name": "Villa Esmee",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-esmee.html",
  "town": "Lloret de Mar",
  "area": "Lloret Blau",
  "lat": 41.74191,
  "lng": 2.81211,
  "persons": 6,
  "personsMax": 6,
  "bedrooms": 3,
  "bathrooms": 2,
  "beds": {
   "Single": 4,
   "Double": 1
  },
  "m2": 160,
  "pool": true,
  "poolType": "Outdoor",
  "pets": true,
  "aircoPaid": false,
  "groups": "geen groepen",
  "minAge": null,
  "rating": 3.5,
  "reviews": 17,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1254/villa-esmee_18808_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1254/villa-esmee_18809_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1254/villa-esmee_18811_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1254/villa-esmee_18807_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1254/villa-esmee_18810_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1254/villa-esmee_18803_X.jpg"
  ]
 },
 {
  "id": "1333",
  "name": "Villa Gabriella",
  "type": "Villa",
  "url": "https://www.costacabana.nl/vakantiehuis/spanje/costa-brava/lloret-de-mar/villa-gabriella.html",
  "town": "Lloret de Mar",
  "area": "Rocca Grossa",
  "lat": 41.71161,
  "lng": 2.85351,
  "persons": 5,
  "personsMax": 5,
  "bedrooms": 1,
  "bathrooms": 1,
  "beds": {
   "Single": 5
  },
  "m2": 55,
  "pool": true,
  "poolType": "Outdoor",
  "pets": false,
  "aircoPaid": false,
  "groups": "groepen ok",
  "minAge": 18,
  "rating": 3.5,
  "reviews": 13,
  "images": [
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1333/villa-gabriella_17014_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1333/villa-gabriella_17013_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1333/villa-gabriella_17016_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1333/villa-gabriella_17017_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1333/villa-gabriella_17015_X.jpg",
   "https://www.costacabana.com/cdn-cgi/image/width=640,height=360,format=auto,fit=scale-down/images/properties/1333/villa-gabriella_17018_X.jpg"
  ]
 }
];
